CREATE DATABASE Weather

Drop database Weather
CREATE TABLE Users (
Username VARCHAR (50)NOT NULL PRIMARY KEY,
UserType VARCHAR (50)NOT NULL,
Password VARCHAR (50)NOT NULL,
);

CREATE TABLE Weather (
ID INT NOT NULL IDENTITY(100,1) PRIMARY KEY,
CityName VARCHAR(50) NOT NULL,
Date Date NOT NULL,
MinTemp INT NOT NULL,
MaxTemp INT NOT NULL,
Precipitation INT NOT NULL,
Humidity INT NOT NULL,
WindSpeed INT NOT NULL,
);


CREATE TABLE FavoriteCities (
ID INT NOT NULL IDENTITY(100,1) PRIMARY KEY,
CityName VARCHAR(50) NOT NULL,
Date Date NOT NULL,
MinTemp INT NOT NULL,
MaxTemp INT NOT NULL,
Precipitation INT NOT NULL,
Humidity INT NOT NULL,
WindSpeed INT NOT NULL,
Username VARCHAR (50) NOT NULL,
FOREIGN KEY (Username) REFERENCES Users (Username)
);
